-- INSERT INTO ganre (name) VALUES ('Romance');
-- INSERT INTO ganre (name) VALUES ('Tragedy');
--
--
-- INSERT INTO scene (name, seats_number) VALUES ('Ivo Andric', 300);
-- INSERT INTO scene (name, seats_number) VALUES ('Branislav Nusic', 300);
-- INSERT INTO scene (name, seats_number) VALUES ('Dragomir Despic', 300);
-- INSERT INTO scene (name, seats_number) VALUES ('Luka Bijelovic', 300);